### ISSUE TITLE
Add layout styles

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-layout#6]
Styles for the layout - such as the sticky footer - should live in this repo.

**Comment by i-like-robots** [comment]
CC @wheresrhys

**Comment by wheresrhys** [comment]
D'you want to put in your universal-doesn't-cause-janky-scroll sticky footer styles and remove my conditional applying of the classes in the template?

**Comment by i-like-robots** [comment]
I think that's nice behaviour to add by default because we'll never really know when it's actually required I guess.

**Comment by i-like-robots** [comment]
#38
