### ISSUE TITLE
Cannot use directional keys to move down list of typeahead results

### ISSUE THREAD

**Issue by andygout** [Financial-Times/n-layout#64]
In branch `header-footer-tpl`, directional keys will move focus to 'London', but when trying to move further down (to 'London riots'), focus does not move and error message `Uncaught TypeError: oLi.firstChild.focus` appears in console.

Seen on Chrome (v.49.0.2623.87)

![screen shot 2016-03-23 at 10 54 37](https://cloud.githubusercontent.com/assets/10484515/13983168/025b4896-f0e6-11e5-89c2-79a8aa123f11.png)

![screen shot 2016-03-23 at 10 54 52](https://cloud.githubusercontent.com/assets/10484515/13983174/0abc2e4c-f0e6-11e5-9963-1bceea667100.png)

**Comment by wheresrhys** [comment]
fixed I think
